/**
 * ModelViewer - Renders GLB 3D models using Google's model-viewer web component.
 * Used to display Tripo3D-generated 3D models in the dashboard.
 */
import { useEffect, useRef } from "react";

interface ModelViewerProps {
  modelUrl: string;
  posterUrl?: string;
  className?: string;
}

export default function ModelViewer({ modelUrl, posterUrl, className = "" }: ModelViewerProps) {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Dynamically import model-viewer to register the web component
    import("@google/model-viewer");
  }, []);

  useEffect(() => {
    if (!containerRef.current) return;

    // Remove any existing model-viewer before creating a new one
    const existing = containerRef.current.querySelector("model-viewer");
    if (existing) existing.remove();

    const mv = document.createElement("model-viewer");
    mv.setAttribute("src", modelUrl);
    mv.setAttribute("alt", "3D Model generated by Tripo3D");
    mv.setAttribute("auto-rotate", "");
    mv.setAttribute("camera-controls", "");
    // Environment and lighting - HDR environment is critical for PBR material visibility
    mv.setAttribute("environment-image", "https://modelviewer.dev/shared-assets/environments/aircraft_workshop_01_1k.hdr");
    mv.setAttribute("skybox-image", "https://modelviewer.dev/shared-assets/environments/aircraft_workshop_01_1k.hdr");
    mv.setAttribute("shadow-intensity", "1");
    mv.setAttribute("shadow-softness", "0.8");
    mv.setAttribute("exposure", "1.5");
    mv.setAttribute("tone-mapping", "commerce");
    // Camera settings - let model-viewer auto-fit the model
    mv.setAttribute("min-camera-orbit", "auto auto 50%");
    mv.setAttribute("max-camera-orbit", "auto auto 200%");
    mv.setAttribute("field-of-view", "45deg");
    // Auto-rotate settings
    mv.setAttribute("auto-rotate-delay", "0");
    mv.setAttribute("rotation-per-second", "30deg");
    // Loading
    mv.setAttribute("loading", "eager");
    mv.setAttribute("reveal", "auto");
    if (posterUrl) mv.setAttribute("poster", posterUrl);

    mv.style.width = "100%";
    mv.style.height = "100%";
    mv.style.minHeight = "400px";
    mv.style.backgroundColor = "#111827"; // slightly lighter dark so model is visible
    mv.style.borderRadius = "8px";
    // CSS custom properties for model-viewer progress bar
    mv.style.setProperty("--progress-bar-color", "#00d4ff");
    mv.style.setProperty("--progress-mask", "none");

    // Log load events for debugging
    mv.addEventListener("load", () => {
      console.log("[ModelViewer] Model loaded successfully");
    });
    mv.addEventListener("error", (e) => {
      console.error("[ModelViewer] Error loading model:", e);
    });

    containerRef.current.appendChild(mv);

    return () => {
      mv.remove();
    };
  }, [modelUrl, posterUrl]);

  return (
    <div ref={containerRef} className={`relative w-full h-full ${className}`} style={{ minHeight: "400px" }} />
  );
}
